"""add_tenant_id_to_tables

Revision ID: 6b1464dad020
Revises: 6fef8df01c1e
Create Date: 2026-05-09 16:01:44.151703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1464dad020'
down_revision: Union[str, Sequence[str], None] = '6fef8df01c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first, fill existing rows, then set NOT NULL
    op.add_column('batches', sa.Column('tenant_id', sa.String(length=100), nullable=True))
    op.execute("UPDATE batches SET tenant_id = 'default' WHERE tenant_id IS NULL")
    op.alter_column('batches', 'tenant_id', nullable=False)
    op.create_index(op.f('ix_batches_tenant_id'), 'batches', ['tenant_id'], unique=False)
    
    op.add_column('certificates', sa.Column('tenant_id', sa.String(length=100), nullable=True))
    op.execute("UPDATE certificates SET tenant_id = 'default' WHERE tenant_id IS NULL")
    op.alter_column('certificates', 'tenant_id', nullable=False)
    op.create_index(op.f('ix_certificates_tenant_id'), 'certificates', ['tenant_id'], unique=False)
    
    op.add_column('delegations', sa.Column('tenant_id', sa.String(length=100), nullable=True))
    op.execute("UPDATE delegations SET tenant_id = 'default' WHERE tenant_id IS NULL")
    op.alter_column('delegations', 'tenant_id', nullable=False)
    op.create_index(op.f('ix_delegations_tenant_id'), 'delegations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delegations_tenant_id'), table_name='delegations')
    op.drop_column('delegations', 'tenant_id')
    op.drop_index(op.f('ix_certificates_tenant_id'), table_name='certificates')
    op.drop_column('certificates', 'tenant_id')
    op.drop_index(op.f('ix_batches_tenant_id'), table_name='batches')
    op.drop_column('batches', 'tenant_id')
    # ### end Alembic commands ###
